"""Investigation kits and their upstream source.

Kits are generated by another team's tooling and consumed here, which makes
"what changed upstream" a real operational question rather than a curiosity. A
kit whose query was verified against a schema months ago is a different artifact
from one verified last week, and an OCE running it has no way to tell.

So this view answers three things:

* what kits exist, and which monitor each one claims;
* whether the local copy differs from the source it came from;
* what the kit actually does -- the base-rate card and the query -- without
  running anything.

Everything here is read-only. Kits are never edited or fetched from this screen:
they belong to the team that generates them, and a console that quietly rewrote
them would fork the source the moment someone upstream edited the original.
"""

from __future__ import annotations

import subprocess
import webbrowser
from dataclasses import dataclass, field
from pathlib import Path

from textual import work
from textual.app import ComposeResult
from textual.binding import Binding
from textual.containers import Horizontal, Vertical
from textual.screen import Screen
from textual.widgets import DataTable, Footer, Header, Static

from ..actions import discover_kits


@dataclass
class KitInfo:
    id: str
    monitor_id: str
    directory: Path
    base_rate: dict[str, str] = field(default_factory=dict)
    has_query: bool = False
    has_runner: bool = False
    has_card: bool = False
    query_lines: int = 0
    #: Populated when the kit directory sits inside a git checkout.
    git_status: str = ""
    last_commit: str = ""
    dirty: bool = False

    @property
    def complete(self) -> bool:
        """A kit missing a piece cannot do its job.

        The card without the query answers "is this normal" but not "what is
        happening now"; the query without the card runs but gives no base rate
        to judge the answer against.
        """
        return self.has_query and self.has_runner and self.has_card


class KitScreen(Screen):
    BINDINGS = [
        Binding("escape,q", "close", "Back"),
        Binding("r", "refresh", "Refresh"),
        Binding("o", "open_folder", "Open folder"),
        Binding("d", "show_diff", "Local changes"),
        Binding("v", "toggle_view", "Card / query"),
    ]

    def __init__(self, config) -> None:
        super().__init__()
        self._config = config
        self._kits: list[KitInfo] = []
        self._view = "card"
        self._diff = ""

    def compose(self) -> ComposeResult:
        yield Header(show_clock=True)
        with Vertical(id="kit-body"):
            yield DataTable(id="kit-table", cursor_type="row", zebra_stripes=True)
            with Horizontal(id="kit-detail"):
                yield Static("", id="kit-summary")
                yield Static("", id="kit-content")
        yield Static("", id="kit-status")
        yield Footer()

    def on_mount(self) -> None:
        self.query_one("#kit-table", DataTable).add_columns(
            "KIT", "MONITOR", "STATE", "QUERY", "SOURCE"
        )
        self.refresh_kits()

    # ------------------------------------------------------------------ load

    def action_refresh(self) -> None:
        self.refresh_kits()

    def refresh_kits(self) -> None:
        if self._config.kits_dir is None:
            self._set_status(
                "[yellow]No kit source configured.[/yellow] "
                "Set OCE_SENTRY_KITS to a kits/ directory to enable runbooks."
            )
            return
        self._set_status("reading kits ...")
        self._load()

    @work(thread=True, exclusive=True, group="kits")
    def _load(self) -> None:
        kits: list[KitInfo] = []
        for action in discover_kits(self._config):
            directory = action.directory
            if directory is None:
                continue
            info = KitInfo(
                id=action.id,
                monitor_id=action.monitor_id,
                directory=directory,
                base_rate=action.base_rate,
                has_query=(directory / "investigate.kql").is_file(),
                has_runner=(directory / "run.ps1").is_file(),
                has_card=(directory / "README.md").is_file(),
            )
            query = directory / "investigate.kql"
            if info.has_query:
                try:
                    info.query_lines = len(query.read_text(encoding="utf-8", errors="replace").splitlines())
                except OSError:
                    pass
            _read_git(info)
            kits.append(info)
        self.app.call_from_thread(self._apply, kits)

    def _apply(self, kits: list[KitInfo]) -> None:
        self._kits = kits
        table = self.query_one("#kit-table", DataTable)
        table.clear()
        for kit in kits:
            state = "[green]ok[/green]" if kit.complete else "[red]incomplete[/red]"
            source = kit.git_status or "[dim]not in git[/dim]"
            table.add_row(
                kit.id[:44],
                (kit.monitor_id or "[dim]none[/dim]")[:34],
                state,
                f"{kit.query_lines}L" if kit.has_query else "[red]missing[/red]",
                source,
            )

        modified = sum(1 for k in kits if k.dirty)
        incomplete = sum(1 for k in kits if not k.complete)
        notes = []
        if modified:
            notes.append(f"[yellow]{modified} modified locally[/yellow]")
        if incomplete:
            notes.append(f"[red]{incomplete} incomplete[/red]")
        suffix = " - " + " - ".join(notes) if notes else ""
        self._set_status(f"{len(kits)} kit(s) from {self._config.kits_dir}{suffix}")
        self._render_detail()

    # ---------------------------------------------------------------- detail

    def _current(self) -> KitInfo | None:
        table = self.query_one("#kit-table", DataTable)
        row = table.cursor_row
        if not self._kits or row is None or row < 0 or row >= len(self._kits):
            return None
        return self._kits[row]

    def on_data_table_row_highlighted(self) -> None:
        self._diff = ""
        self._render_detail()

    def action_toggle_view(self) -> None:
        self._view = "query" if self._view == "card" else "card"
        self._diff = ""
        self._render_detail()

    def _render_detail(self) -> None:
        summary = self.query_one("#kit-summary", Static)
        content = self.query_one("#kit-content", Static)

        kit = self._current()
        if kit is None:
            summary.update("No kit selected.")
            content.update("")
            return

        lines = [
            f"[b]{_escape(kit.id)}[/b]",
            "",
            f"monitor   {_escape(kit.monitor_id) if kit.monitor_id else '(none declared)'}",
            f"card      {'yes' if kit.has_card else '[red]missing[/red]'}",
            f"query     {kit.query_lines} lines" if kit.has_query else "query     [red]missing[/red]",
            f"runner    {'run.ps1' if kit.has_runner else '[red]missing[/red]'}",
        ]
        if kit.base_rate:
            lines.append("")
            lines.append("[b]base rate[/b]")
            for key, value in kit.base_rate.items():
                if key != "tsg":
                    lines.append(f"  {key}: {value}")
        if kit.last_commit:
            lines += ["", "[b]source[/b]", f"  {_escape(kit.last_commit)}"]
        if kit.dirty:
            lines.append("  [yellow]modified locally - press d to see the change[/yellow]")
        lines += ["", f"[dim]{kit.directory}[/dim]"]
        summary.update("\n".join(lines))

        if self._diff:
            content.update(f"[b]Local changes[/b]\n\n{_escape(self._diff)}")
            return

        if self._view == "query":
            content.update(f"[b]investigate.kql[/b]\n\n{_escape(_read(kit.directory / 'investigate.kql'))}")
        else:
            content.update(f"[b]README.md[/b]\n\n{_escape(_read(kit.directory / 'README.md'))}")

    # --------------------------------------------------------------- actions

    def action_show_diff(self) -> None:
        """Show what differs from the committed copy.

        The collaboration case: an OCE tweaks a kit's query locally to get
        through an incident, and that change is either worth proposing upstream
        or worth discarding. Either way it should be visible.
        """
        kit = self._current()
        if kit is None:
            return
        diff = _git(["diff", "--", "."], kit.directory)
        if not diff.strip():
            diff = _git(["status", "--short", "--", "."], kit.directory)
        self._diff = diff.strip() or "No local changes against the committed copy."
        self._render_detail()

    def action_open_folder(self) -> None:
        kit = self._current()
        if kit:
            webbrowser.open(kit.directory.as_uri())

    def action_close(self) -> None:
        self.dismiss()

    def _set_status(self, message: str) -> None:
        self.query_one("#kit-status", Static).update(message)


def _read(path: Path, limit: int = 6000) -> str:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return "(unreadable)"
    return text[:limit] + ("\n... truncated" if len(text) > limit else "")


def _git(args: list[str], cwd: Path) -> str:
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=str(cwd),
            capture_output=True,
            text=True,
            timeout=20,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return ""
    return result.stdout if result.returncode == 0 else ""


def _read_git(info: KitInfo) -> None:
    """Best effort. A kit outside a checkout is still a usable kit."""
    status = _git(["status", "--porcelain", "--", "."], info.directory)
    if status is None:
        return
    info.dirty = bool(status.strip())

    log = _git(["log", "-1", "--format=%h %ad %s", "--date=short", "--", "."], info.directory)
    info.last_commit = log.strip()[:80]

    if info.dirty:
        info.git_status = "[yellow]modified[/yellow]"
    elif info.last_commit:
        info.git_status = info.last_commit.split(" ")[1] if " " in info.last_commit else "tracked"
    else:
        info.git_status = ""


def _escape(text: str) -> str:
    return str(text).replace("[", r"\[")
